[tasks.install]
run = '''
xcodebuild -scheme KarukanIM -configuration Release build | xcpretty
killall KarukanIM; sleep 1; open "$HOME/Library/Input Methods/KarukanIM.app"
'''

[tasks.clean]
run = '''
xcodebuild -scheme KarukanIM clean | xcpretty
'''
